### ISSUE TITLE
MaterialのTransparentにテクスチャがついてるときalpha要素を持っている時にglTFのalphaModeがBLENDにならない

### ISSUE THREAD

**Issue by kioku-systemk** [kashikacojp/glTF-Maya-Exporter#48]
Color/transparentに同一のテクスチャがセットされていると
MAYAでいいかんじに透明になるが、glTFでalphaModeがセットされないと
glTFのビューワーで透明にならない。

**Comment by kioku-systemk** [comment]
Transparentにテクスチャがついている場合は強制的にalphaMode=BLENDにすればよい？

**Comment by kioku-systemk** [comment]
現状、glTF出力時にbaseColorのAの値を見て判定しているだけなので、ここでtransparentなテクスチャがついているか判定すればよい気がする。
```
if (A >= 1.0f) {
    nd["alphaMode"] = picojson::value("OPAQUE");
} else {
    nd["alphaMode"] = picojson::value("BLEND");
}
```

また、Transparentなテクスチャを取得していないので、取得するようにする。

**Comment by ototoi** [comment]
テクスチャをpng にした時に"Blend"にする。

**Comment by kioku-systemk** [comment]
emissiveにだけpngテクスチャがついているときにBLENDにならない。
しかし、emissiveはRGB要素しか見ないからこれで正常なのかも？
emissiveでBLENDで抜きたいときは、baseColorにも同じpngテクスチャを設定すればよい。
