### ISSUE TITLE
アニメーションデータを１つにまとめられるようにするオプションを追加

### ISSUE THREAD

**Issue by kioku-systemk** [kashikacojp/glTF-Maya-Exporter#49]
現状ノードごとにアニメーションが複数のチャンネルで、個別に出力されているが、
WebAR向けのglTFでは１つにまとめる必要がある。（１つしか再生されない）
エクスポータ出力時のオプション設定で、
チャンネルを１つにまとめてエクスポートするオプションの機能を追加する

**Comment by ototoi** [comment]
<img width="438" alt="スクリーンショット 2019-11-18 16 08 05" src="https://user-images.githubusercontent.com/343247/69031540-a8c47c80-0a1d-11ea-8e18-48980745006c.png">
