### ISSUE TITLE
unlitマテリアルを設定したい

### ISSUE THREAD

**Issue by kioku-systemk** [kashikacojp/glTF-Maya-Exporter#50]
特定のマテリアルを設定、または特定のマテリアルで特定の設定をした場合に `KHR_materials_unlit` https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit
拡張でマテリアルをエクスポートするようにする方法を考える。

**Comment by ototoi** [comment]
- 標準Lambert系シェーダが割り振られている時、Ambientが(1,1,1)の時
- aiStandardの時、`Base`, `Specular`, `Transparent`のweightが０でかつ`Emission`のweightが1の時

**Comment by kioku-systemk** [comment]
ambient=1,1,1だと白っぽくならないかな?
設定が難しいと忘れそうかも
unlit系のシェーダってなんでしたっけ？

**Comment by kioku-systemk** [comment]
aiFlatというArnoldマテリアルがある。（Unlit用)
Mayaだと Surface Shaderの Out Colorと Out Transparencyに設定すればそのまま出力されそう。

**Comment by kioku-systemk** [comment]
SurfaceShader対応した
