### ISSUE TITLE
Alpha Cutoffの設定をできるようにする

### ISSUE THREAD

**Issue by kioku-systemk** [kashikacojp/glTF-Maya-Exporter#51]
カラーテクスチャのAlpha Cutoffの設定をできるようにする
`alphaMode="BLEND"` のときは半透明になるが、CUTOFFはされない。
CutOffは `alphaMode="MASK"` のときのみ有効。
これにMAYAのマテリアル設定で対応する方法を考え実装を行う。
Cutoffの値は `0.0~1.0` の値で設定可能なこと

**Comment by ototoi** [comment]
マテリアルの追加アトリビュートに`alphaMask`(bool) を追加し、`true`にすると`alphaMode="MASK"`になる。
さらに`alphaCutoff`(float)を追加でCutoffの値を変更できる。
