### ISSUE TITLE
Emissionテクスチャが出力されていない

### ISSUE THREAD

**Issue by kioku-systemk** [kashikacojp/glTF-Maya-Exporter#54]
emissiveFactorは出力されているが、
テクスチャを設定した際に、emissiveTextureが設定されておらず、
emissiveFactor=1.0がでるだけになっている。
imagesは出力されているので、emissiveTextureを設定し忘れている気がする。

**Comment by ototoi** [comment]
@kioku-systemk 
修正は実際はKashikaNativeLibの方でやりましたので、こちらの修正はわずかです。
